[WIP] document system for providing metered billing data to Odoo16
appuio/appuio-io-docs pull request #159
Opened 2023-10-18 16:00 UTC by HappyTetrahedron

## Checklist

- [ ] Try to isolate changes into separate PRs (to build a better changelog).
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `change`, `decision`, `requirement/quality`, `requirement/functional`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues if applicable.

2023-10-20 13:43 UTC, simu approved these changes
LGTM overall, but it probably makes sense if at least a 2nd engineer and @corvus-ch review this as well.

2023-10-20 14:31 UTC, tobru approved these changes

2023-10-23 08:55 UTC, corvus-ch requested changes
Nice work as far as it concerns the content. From a structure perspective, we should put things in different locations.

* The generic description of the ETL data flow probably should go into https://docs.central.vshn.ch (Metered Billing > Data Flow).
* The page on APPUiO Managed, should go into https://docs.central.vshn.ch.

You built the content for APPUiO Managed on the one of APPUiO Cloud. But the product APPUiO Cloud is builds on top of APPUiO Managed. So the documentation for billing should also work in that order (for historical reasons, it was not the case so far).

This then also raises the question if `appuio_cloud_reporting` is the appropriate key. Maybe, `appuio_managed_reporting` is more suitable. Depending on how generic our implementation becomes, it might also be used for AppCat, so an even more generic name might be in order.

2023-10-23 08:55 UTC, corvus-ch commented on docs/modules/ROOT/pages/references/architecture/metering-data-flow.adoc
> +<4> Used for grouping lines item on the final invoice
```suggestion
<4> Used for grouping line items on the final invoice
```

2023-10-23 08:55 UTC, corvus-ch commented on docs/modules/ROOT/pages/references/architecture/metering-data-flow-appuio-cloud.adoc
> +Each query result represents an usage data record, to be transformed and loaded into the target system.
```suggestion
Each query result represents a usage data record, to be transformed and loaded into the target system.
```

2023-10-24 13:54 UTC, merged